### ISSUE TITLE
Test assembly should be in a child path of the base folder

### ISSUE THREAD

**Issue by Lexy2** [3CS-Software/test-out#9]
...looks like it, but the documentation does mention it, so it leads to erroneous configurations.

Additionally, I've been told informally that test assembly must be a path relative to the base path only and specifying a full path breaks the app.

**Comment by mstancombe** [comment]
There are several tasks here
- [x] the 'Running Tests' section in the doco should be fleshed out to make it explicit that the test dll has to be within the base folder, as that folder is the only part that is shipped around
- [x] the --test-assembly parameter should accept a full path, and log an error if that full path doesn't sit in the --base-path folder.  If it does sit in that folder, it should strip the base path portion, and continue the test invocation.

**Comment by mstancombe** [comment]
https://github.com/3CS-Software/test-out/releases/tag/v0.7.4-alpha
